modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]]

modId="expansion"
version="${file.jarVersion}"
displayName="Expansion"
logoFile="Expasionmod.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"

description='''
'''
[[dependencies.expansion]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
